name: get_it_demo
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.2
  cupertino_icons: ^1.0.0
  # Injectable trabalha junto com o GetIt e outras dependências
  injectable: ^1.0.5
  get_it: ^5.0.1

dev_dependencies:
  injectable_generator: ^1.0.6
  build_runner:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
